### PR TITLE
Create Potential Projects.md

### LINKED ISSUE #3: Determine a concrete astronomy application
_Astronomy, even just Adaptive Optics, is a broad field. Narrow it down!_

We need to scope the course to a specific algorithm or technique that shows unknown promise for GPU acceleration. The scope in the CSC586C course last semester is very indicative. This involves a combination of:

 * asking Herzberg contacts (e.g., Matthias) about "hot" problems
 * scanning proceedings of recent periodicals (e.g., AO4ELT conference)
 * clever keyword searches in Google Scholar

### PR DESCRIPTION
**Pull request by mehrler12**
@sean-chester  Hey! Here's some of the potential projects and papers! Let me know if you have more

_(This pull request resolves #3 )_

### CODE REVIEW

**Comment by sean-chester** [comment]
This pull request relates to issue #2 .

**Comment by sean-chester** [comment]
@mehrler12 , my friend at TMT referred my question on to one of his colleagues (specialists) at TMT in California who came back with the following response:

> Accelerating the RTC using matrix vector multiply is relatively straightforward on CPUs or GPUs, however, implementing the iterative algorithms is more challenging but may be necessary for next generation AO systems, such as MOAO which needs to control a lot of DMs. People are also interested in Kalman Filter based AO control that requires orders of magnitude more computations. See [this paper](https://www.researchgate.net/publication/236929368_Distributed_Kalman_filtering_compared_to_Fourier_domain_preconditioned_conjugate_gradient_for_laser_guide_star_tomography_on_extremely_large_telescopes).

**Comment by mehrler12** [comment]
Yeah, space lasers for shooting down garbage will always have my heart but I think this one is the way to go. There's a pretty indepth description of the algorithm in there and a quick search finds quite a bit on the gpu sutability of Kalmann filters. Thanks for finding that! And thanks to your friend as well!

**Comment by sean-chester** [comment]
Haha, yeah, that would be a pretty cool project to describe in a job interview! :)

But note that he suggested two topics in that paragraph:
  * iterative methods (e.g., _iterative gradient descent_), which he figures is necessary for multi-object adaptive optics. That's what we were working on with Yvonne a decade ago, so I know it's very relevant to Herzberg, but I also worry about tackling a problem as a class project if it hasn't been solved in a decade
 * the kalmann filter methods, which looks like low-hanging fruit on the GPU so needs a deeper lit search. It sounds like this is particularly interesting to the group in Pasadena (and CNRS/France).

Either of these could be promising. Maybe you could expand `Potential Projects.md` with a quick survey of a couple papers each (including the one written by the Pasadena folk) so that we can pick one of these five projects confidently during Tuesday's meeting?

I haven't screened these two papers closely, but they have high citation rates. The second author of the first paper was our potential collaborator at Herzberg back then. The second paper might have software accompanying it? Both may help in describing iterative moao as an alternative?

 * https://www.spiedigitallibrary.org/conference-proceedings-of-spie/9148/91486C/Object-oriented-Matlab-adaptive-optics-toolbox/10.1117/12.2054470.short
 * http://ao4elt3.arcetri.astro.it/proceedings/fulltext_13173.pdf

**Comment by mehrler12** [comment]
That sounds good! I'll work on that! Thanks

**Comment by sean-chester** [comment]
@mehrler12 , thanks for the updates and digging! One outstanding question re: kalmann filters for MOAO:

> Is there much work in this area by others than Gilles, Ellerbroek, and Massioni?

When determining whether an area is "hot" or "emerging" it is important to note not just if there are a lot of papers on the topic but how many different groups seem to be interested in it. Publications are a reasonable proxy for that.

**Comment by mehrler12** [comment]
Yeah it seems like there's a few! There's this one that has Rigault as an author, he's basically "the guy" for adaptive optics https://www.researchgate.net/publication/323347638_Modeling_and_identification_of_adaptive_optics_systems_to_satisfy_distributed_Kalman_filter_model_structural_constraints
As well as the french group you mentioned that has a few papers https://arxiv.org/pdf/1408.7069.pdf looking into more

**Review by sean-chester — APPROVED** [review]

**Pull request merged**
